"""
Fidoo7 Driver - Setup Configuration

Production-grade setup.py for packaging and distribution.
Follows Python packaging best practices and setuptools conventions.
"""

from setuptools import setup, find_packages
from pathlib import Path

# Read long description from README
repo_dir = Path(__file__).parent.resolve()
long_description = (repo_dir / "README.md").read_text(encoding="utf-8")

# Read requirements from requirements.txt
requirements = [
    line.strip()
    for line in (repo_dir / "requirements.txt").read_text(encoding="utf-8").split("\n")
    if line.strip() and not line.startswith("#")
]

setup(
    # Package metadata
    name="fidoo7-driver",
    version="1.0.0",
    description="Python driver for Fidoo expense management and prepaid card system API",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="Generated by Claude Code",
    author_email="noreply@anthropic.com",
    license="MIT",
    url="https://github.com/anthropics/fidoo7-driver",
    project_urls={
        "Bug Tracker": "https://github.com/anthropics/fidoo7-driver/issues",
        "Documentation": "https://github.com/anthropics/fidoo7-driver/blob/main/README.md",
        "Source Code": "https://github.com/anthropics/fidoo7-driver",
    },

    # Python version
    python_requires=">=3.8",

    # Package discovery
    packages=find_packages(where="."),
    include_package_data=True,

    # Dependencies
    install_requires=requirements,

    # Optional dependencies
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-cov>=4.0.0",
            "black>=22.0.0",
            "flake8>=4.0.0",
            "mypy>=0.950",
            "isort>=5.10.0",
        ],
        "docs": [
            "sphinx>=4.5.0",
            "sphinx-rtd-theme>=1.0.0",
        ],
    },

    # Classifiers for PyPI
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Office/Business :: Financial",
        "Topic :: Internet :: WWW/HTTP",
    ],

    # Keywords for PyPI search
    keywords=[
        "fidoo",
        "expense-management",
        "api-client",
        "rest-api",
        "prepaid-cards",
        "financial",
    ],

    # Entry points (CLI tools, if needed in future)
    entry_points={
        "console_scripts": [
            # Example: "fidoo-cli=fidoo7.cli:main",
        ],
    },

    # Additional metadata
    zip_safe=False,
)
